# Generated by Django 4.1.2 on 2022-12-05 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cienciaficcion',
            name='sinopsis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cienciaficcion',
            name='url_portada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='distopia',
            name='sinopsis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='distopia',
            name='url_portada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fantasia',
            name='sinopsis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fantasia',
            name='url_portada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terror',
            name='sinopsis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='terror',
            name='url_portada',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
