# Generated by Django 4.1.3 on 2022-12-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0002_alter_cienciaficcion_sinopsis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
