# Generated by Django 4.1.3 on 2022-12-08 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0003_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cienciaficcion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 8, 1, 3, 52, 529051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cienciaficcion',
            name='publicacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 1, 4, 1, 451591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distopia',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 8, 1, 4, 7, 73050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distopia',
            name='publicacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 1, 4, 9, 569569, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fantasia',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 8, 1, 4, 11, 962056, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fantasia',
            name='publicacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 1, 4, 20, 806046, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terror',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 8, 1, 4, 32, 82565, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terror',
            name='publicacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 1, 4, 37, 51048, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
