# Generated by Django 4.1.3 on 2022-12-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0004_cienciaficcion_date_cienciaficcion_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cienciaficcion',
            old_name='date',
            new_name='publicacion_en_foro',
        ),
        migrations.RenameField(
            model_name='distopia',
            old_name='date',
            new_name='publicacion_en_foro',
        ),
        migrations.RenameField(
            model_name='fantasia',
            old_name='date',
            new_name='publicacion_en_foro',
        ),
        migrations.RenameField(
            model_name='terror',
            old_name='date',
            new_name='publicacion_en_foro',
        ),
    ]
