# Generated by Django 4.1.3 on 2022-12-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0005_rename_date_cienciaficcion_publicacion_en_foro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cienciaficcion',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='distopia',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='fantasia',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='terror',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
    ]
